import { gmail } from './gmail.js';
import { config } from './config.js';

export interface SummaryItem {
  threadId: string;
  feedbackPreview: string;
  triageClass: string;
  outcome:
    | 'pr_opened'
    | 'draft_pr_needs_human'
    | 'skipped_vague'
    | 'skipped_noise'
    | 'error'
    | 'over_cap'
    | 'budget_exceeded'
    | 'deferred';
  prUrl?: string;
  reason?: string;
  filesChanged?: string[];
  buildAttempts?: number;
  tokensUsed?: number;
}

export interface SummaryReport {
  runStartedAt: string;
  runFinishedAt: string;
  totalEmails: number;
  prsOpened: number;
  draftPrs: number;
  skipped: number;
  errors: number;
  totalTokens: number;
  items: SummaryItem[];
}

export async function sendSummaryEmail(report: SummaryReport): Promise<void> {
  const subject = renderSubject(report);
  const body = renderBody(report);
  const raw = buildRfc822(config.summaryRecipient, subject, body);
  const g = await gmail();
  await g.users.messages.send({
    userId: 'me',
    requestBody: { raw },
  });
}

function renderSubject(r: SummaryReport): string {
  const date = r.runStartedAt.slice(0, 10);
  const parts = [
    r.prsOpened > 0 ? `${r.prsOpened} PR${r.prsOpened === 1 ? '' : 's'}` : null,
    r.draftPrs > 0 ? `${r.draftPrs} needs-human` : null,
    r.skipped > 0 ? `${r.skipped} skipped` : null,
    r.errors > 0 ? `${r.errors} error${r.errors === 1 ? '' : 's'}` : null,
  ].filter(Boolean);
  const tag = parts.length === 0 ? 'no feedback' : parts.join(' · ');
  return `[wte-feedback] ${date} — ${tag}`;
}

function renderBody(r: SummaryReport): string {
  const lines: string[] = [];
  lines.push(`Run started:  ${r.runStartedAt}`);
  lines.push(`Run finished: ${r.runFinishedAt}`);
  lines.push(`Emails seen:  ${r.totalEmails}`);
  lines.push(`PRs opened:   ${r.prsOpened}`);
  lines.push(`Draft PRs:    ${r.draftPrs}  (needs-human)`);
  lines.push(`Skipped:      ${r.skipped}`);
  lines.push(`Errors:       ${r.errors}`);
  lines.push(`Tokens used:  ${r.totalTokens}`);
  lines.push('');
  if (r.items.length === 0) {
    lines.push('Nothing to report.');
    return lines.join('\n');
  }
  lines.push('───────────────────────────────────────────');
  for (let i = 0; i < r.items.length; i++) {
    const it = r.items[i]!;
    lines.push(`#${i + 1}  [${it.outcome.toUpperCase()}]  ${it.triageClass}`);
    lines.push(`     thread: ${it.threadId}`);
    lines.push(`     feedback: ${truncate(it.feedbackPreview, 200)}`);
    if (it.prUrl) lines.push(`     PR: ${it.prUrl}`);
    if (it.filesChanged && it.filesChanged.length > 0) {
      lines.push(`     files: ${it.filesChanged.join(', ')}`);
    }
    if (typeof it.buildAttempts === 'number') {
      lines.push(`     build attempts: ${it.buildAttempts}`);
    }
    if (typeof it.tokensUsed === 'number') {
      lines.push(`     tokens: ${it.tokensUsed}`);
    }
    if (it.reason) lines.push(`     reason: ${it.reason}`);
    lines.push('');
  }
  lines.push('───────────────────────────────────────────');
  lines.push('Generated by feedback-agent. PRs require manual review before merge.');
  return lines.join('\n');
}

function buildRfc822(to: string, subject: string, body: string): string {
  const lines = [
    `To: ${to}`,
    `From: ${to}`,
    `Subject: ${encodeSubject(subject)}`,
    'MIME-Version: 1.0',
    'Content-Type: text/plain; charset=UTF-8',
    'Content-Transfer-Encoding: 7bit',
    '',
    body,
  ];
  const raw = lines.join('\r\n');
  // Gmail send wants base64url
  return Buffer.from(raw, 'utf8').toString('base64url');
}

function encodeSubject(s: string): string {
  // RFC 2047 encoded-word for non-ASCII (rare here, but cheap).
  if (/^[\x20-\x7e]*$/.test(s)) return s;
  return `=?UTF-8?B?${Buffer.from(s, 'utf8').toString('base64')}?=`;
}

function truncate(s: string, n: number): string {
  const oneLine = s.replace(/\s+/g, ' ').trim();
  if (oneLine.length <= n) return oneLine;
  return oneLine.slice(0, n - 1) + '…';
}
